baseURL = "https://ummadum.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ummadum Carpooling"
theme = "ummadum"
googleAnalytics = ""


[imaging]
resampleFilter = "box"
quality = 10


[languages.en]
weight = 0
languageName = "English"
contentDir = "content/en"

[[languages.en.menu.main]]
url    = "#how-does-it-work"
name   = "How does it work"
weight = 0

[[languages.en.menu.main]]
url    = "#partner"
name   = "Partner"
weight = 10

[[languages.en.menu.main]]
url    = "#faq"
name   = "FAQ"
weight = 20

[[languages.en.menu.main]]
url    = "/book"
name   = "Book a travel"
weight = 30

[languages.de]
weight = 10
contentDir = "content/de/"
languageName = "Deutsch"

[[languages.de.menu.main]]
url    = "#how-does-it-work"
name   = "Wie es funktioniert"
weight = 0

[[languages.de.menu.main]]
url    = "#partner"
name   = "Partner"
weight = 10

[[languages.de.menu.main]]
url    = "#faq"
name   = "FAQ"
weight = 20

[[languages.de.menu.main]]
url    = "/book"
name   = "Buche eine Fahrt"
weight = 30

[languages.it]
weight = 20
contentDir = "content/it/"
languageName = "Italiano"

[[languages.it.menu.main]]
url    = "#how-does-it-work"
name   = "Come funziona"
weight = 0

[[languages.it.menu.main]]
url    = "#partner"
name   = "Partner"
weight = 10

[[languages.it.menu.main]]
url    = "#faq"
name   = "Domande frequenti"
weight = 20

[[languages.it.menu.main]]
url    = "/book"
name   = "Prenota un viaggio"
weight = 30

[[languages.en.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Privacy"
weight = 10

[[languages.en.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Cookies"
weight = 20

[[languages.en.menu.footer]]
url    = "/contact"
name   = "Contact"
weight = 30

[[languages.de.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Privacy"
weight = 10

[[languages.de.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Cookies"
weight = 20

[[languages.de.menu.footer]]
url    = "/contact"
name   = "Kontakt"
weight = 30

[[languages.it.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Privacy"
weight = 10

[[languages.it.menu.footer]]
url    = "https://noi.bz.it/privacy-cookie-policy"
name   = "Cookies"
weight = 20

[[languages.it.menu.footer]]
url    = "/contact"
name   = "Contatto"
weight = 30
